kenalin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import status.urls as status
import aboutme.urls as aboutme

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^aboutme/', include(aboutme, namespace='aboutme')),
    url(r'^academic/', include('academic.urls', namespace='academic')),
    url(r'^auth/', include('main.urls', namespace='main')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^$', RedirectView.as_view(url='auth/', permanent='True')),
]

main/urls.py
from django.conf.urls import url
from .custom_auth import auth_login, auth_logout
from .views import index, login_page
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^sso/$', login_page, name='sso'),
    url(r'^login/$', auth_login, name='login'),
    url(r'^logout/$', auth_logout, name='logout'),
]

status/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
    url(r'^(?P<username>.*)/$', index, name='status'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status', delete_status, name='delete_status'),
]

status/models.py
from django.db import models
from main.models import User

# Create your models here.
class Status(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.TextField(max_length=140)
    created_date = models.DateTimeField(auto_now_add=True)

status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'  write here...',
        'id': 'field'
    }
    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

status/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from main.models import User
from .models import Status
from .forms import Status_Form

response = {}

def index(request, username):
	response['login_name'] = request.session.get('user_login')
	if 'user_login' in request.session:
		name = request.session.get('user_login', None)
		print(username)
		print(name)
		response['show_form'] = False if name == username else True

	user = User.objects.get(username=username)
	status = Status.objects.filter(username=username).order_by('-id')
	response['image'] = user.profile_pic
	response['name'] = user.username
	response['status'] = status
	response['status_form'] = Status_Form		
	html = 'status/status.html'
	return render(request, html, response)

def add_status(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['isi'] = request.POST['status']
		username = request.session['user_login']
		user = User.objects.get(username=username)
		status = Status(username=user,status=response['isi'])
		status.save()
	return HttpResponseRedirect('/status/'+username)

def delete_status(request):
	if (request.method == 'POST'):
		username = request.session['user_login']
		statusId = request.POST['status-id']
		status = Status.objects.get(id=statusId)
		status.delete()
		return HttpResponseRedirect('/status/'+username)
	elif (request.method == 'GET'):
		username = request.session['user_login']
		return HttpResponseRedirect('/status/'+username)

status/templates/status/status.html
{% extends "main/layout/base.html" %}
{% load static %}


{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
<section name="input-status" id="input-status">
        <form id="form" method="POST" action="{% url 'status:add_status' %}">
            <h3><b>What's on your mind?</b></h3>
            {% csrf_token %}
            {{ status_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-md btn-info" value="Post">
        </form>
</section>
<section name="list-status" id="list-status">
    <div class="template">
        <h3><b>{{ name }}'s Timeline</b></h3>
            <div class="in"></div>
                {% if status %}
                    {% for data in status %}
                        <div class="status-list">
                            <div class="media">
                                <div class="media-left media-middle">
                                    <img src="{{ image }}" class="media-object" style="width:60px">
                                </div>
                                <div class="media-body">
                                    <h5 class="media-heading"><b>{{ name }}</b></h5>
                                    <p>{{ data.status }}</p>
                                    <div class="status-list-date-added">
                                        Posted on {{data.created_date}}
                                    </div>
                                    <br id="space-status">
                                    <div class="status-list-delete">
                                    <form id="delete-status" method="POST" action="{% url 'status:delete_status' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name=status-id value="{{data.id}}">
                                        <input id="delete" type="image" src="https://i.imgur.com/ymh9Aa9.png" style="width: 16px">
                                    </form>
                                </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="alert alert-danger text-center">
                        <strong>Oops!</strong> Belum ada status.
                    </div>
                {% endif %}
            </div>
        </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var show_form = '{{ show_form }}'
        if (show_form == 'True') {
            console.log(show_form)
            $('#input-status').hide();
            $('.status-list-delete').hide();
        }
        else{
            $('#input-status').show();
            $('.status-list-delete').show();
        }
    });
</script>
{% endblock %}

status/templates/status/status_public.html
{% extends "main/layout/base.html" %}
{% load static %}


{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
<section name="list-status" id="list-status">
    <div class="template">
        <h3><b>Timeline</b></h3>
            {% if status %}
                {% for data in status %}
                    <div class="status-list">
                        <div class="media">
                            <img class="d-flex align-self-top mr-3" src="{{image}}" alt="Generic placeholder image" style="width:60px">
                            <div class="media-body">
                                <h6 class="mt-0"><b>{{name}}</b></h6>
                                <p>{{data.status}}</p>
                                <div class="status-list-date-added">
                                    Posted on {{data.created_date}}
                                </div>
                            </div>
                            <!--
                            <div class="status-list-delete">
                                <form id="delete-status" method="POST" action="{% url 'status:delete_status' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name=status-id value="{{data.id}}">
                                    <input id="delete" type="image" src="https://i.imgur.com/ymh9Aa9.png" style="width: 16px">
                                </form>
                            </div>-->
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Belum ada status.
            </div>
            {% endif %}
        </div>
</section>
{% endblock %}