kenalin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import status.urls as status
import aboutme.urls as aboutme

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^aboutme/', include(aboutme, namespace='aboutme')),
    url(r'^academic/', include('academic.urls', namespace='academic')),
    url(r'^auth/', include('main.urls', namespace='main')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^$', RedirectView.as_view(url='auth/', permanent='True')),
]

main/urls.py
from django.conf.urls import url
from .custom_auth import auth_login, auth_logout
from .views import index, login_page
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^sso/$', login_page, name='sso'),
    url(r'^login/$', auth_login, name='login'),
    url(r'^logout/$', auth_logout, name='logout'),
]

main/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


class User(models.Model):
    username = models.CharField(max_length=20, unique=True, primary_key=True)
    npm = models.CharField(max_length=20, unique=True)
    profile_pic = models.URLField(
        default="https://www.lausanne.org/wp-content/uploads/2017/04/anonymous-icon-150x150.jpg")
    flag_nilai = models.BooleanField(default=False)
    name = models.CharField(max_length=27, default="Kosong")
    expertise = models.ManyToManyField('Expertise', default="Kosong")
    email = models.EmailField(default="Kosong")
    linkedin_profile = models.URLField(default="Kosong")


LEVEL_CHOICES = (
    ('1', 'Beginner'),
    ('2', 'Intermediate'),
    ('3', 'Advanced'),
    ('4', 'Expert')
)

class Expertise(models.Model):
    expertise = models.CharField(max_length=20)
    level = models.CharField(max_length=20, choices=LEVEL_CHOICES, default='1')

    def __str__(self):
        return str(self.expertise)

main/views.py
from django.shortcuts import render

res = {}
# Create your views here.
def index(request):
	html = 'main/landing_page.html'
	return render(request, html, res)

def login_page(request):
	html = 'main/login.html'
	return render(request, html, res)

main/templates/main/layout/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Kenalin">

    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>

    <!-- LinkedIN API script -->
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key:   810ml0iwk37thr
        onLoad:    onLinkedInLoad
        authorize: true
    </script>

    <title>
        kenal.in
    </title>
</head>
<body>
<div id="wrapper">
    <div id="header">

        <header class="header-search">

            <div class="header-limiter">
                <nav>
                    <a class='company_logo' href="#"><img class="company_logo_img"
                                                          src="https://image.flaticon.com/icons/svg/511/511131.svg"></a>
                </nav>

                <div class="header-user-menu">
                    <img src="https://www.lausanne.org/wp-content/uploads/2017/04/anonymous-icon-150x150.jpg"
                         alt="User Image"/>
                    <ul>
                        <li><a href="{% url 'main:logout' %}" class="highlight">Logout</a></li>
                        <li><a href="#">Settings</a></li>
                    </ul>
                </div>
                <form>
                    <input id="searchinput" placeholder="Search!" name="search">
                </form>
            </div>
        </header>
    </div>
    <div id="content" class="container">
        <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </content>
    </div>
</div>
<div id="footer">
    <footer>
        <div class="footer-copyright">
            <a>
                <center><strong>© 2017 kenal.in</strong></center>
            </a>
        </div>
    </footer>
</div>
</body>

<script>

    $(document).ready(function () {
        var a = window.location.pathname.split('/')
        var b = a[a.length-2]
        html = '<a id="home" href="/aboutme/'+b+'">Home</a>'+
                    '<a id="academic" href="/academic/'+b+'">Academic</a>'+
                    '<a id="Status" href="/status/'+b+'">Status</a>'
        $('.company_logo').append(html);

        $('.header-search form').on('click', function (e) {
            if (e.target == this) {
                $(this).find('input').toggle();
            }
        });

        $('#searchinput').keypress(function (e) {
            var key = e.which;
            if (key == 13)  // the enter key code
            {
                e.preventDefault();
                var searchkey = $('#searchinput').val();
                window.location.replace('/search/' + searchkey);
            }
        });

    });

</script>