aboutme/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add-expertise/(?P<expertise>.*)/(?P<level>.*)/$', addExpertise, name='addExpertise'),
    url(r'^edit/', edit, name='edit'),
    url(r'^edit-profile', edit_profile, name='edit-profile'),
    url(r'^show-grades', showGrades, name='show-grades'),
    url(r'^(?P<username>.*)/$', index, name='index'),
]

kenalin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import status.urls as status
import aboutme.urls as aboutme

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^aboutme/', include(aboutme, namespace='aboutme')),
    url(r'^academic/', include('academic.urls', namespace='academic')),
    url(r'^auth/', include('main.urls', namespace='main')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^$', RedirectView.as_view(url='auth/', permanent='True')),
]

main/urls.py
from django.conf.urls import url
from .custom_auth import auth_login, auth_logout
from .views import index, login_page
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^sso/$', login_page, name='sso'),
    url(r'^login/$', auth_login, name='login'),
    url(r'^logout/$', auth_logout, name='logout'),
]

aboutme/models.py
from django.db import models

# Create your models here.

aboutme/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from main.models import User, Expertise

response = {}


# Create your views here.
def index(request, username):
    user_count = User.objects.filter(username=username)
    if user_count == 0:
        user = User.objects.create(username=username)
        user.save()
    else:
        user = user_count.first()

    response['username'] = user.username
    response['npm'] = user.npm
    response['profile_pic'] = user.profile_pic
    response['flag_nilai'] = user.flag_nilai
    response['name'] = user.name
    response['expertise'] = user.expertise.all()
    response['email'] = user.email
    response['linkedin_profile'] = user.linkedin_profile

    if 'user_login' in request.session:
        login = request.session.get('user_login')
        response['login_name'] = login
        if login == username:
            response['show_edit'] = True
        else:
            response['show_edit'] = False

    html = 'aboutme/aboutme.html'
    return render(request, html, response)


def edit(request):
    if 'user_login' in request.session:
        username = request.session.get('user_login', None)
        user = User.objects.get(username=username)

        response['username'] = user.username
        response['npm'] = user.npm
        response['profile_pic'] = user.profile_pic
        response['flag_nilai'] = user.flag_nilai
        response['name'] = user.name
        response['expertise'] = user.expertise.all()
        response['email'] = user.email
        response['linkedin_profile'] = user.linkedin_profile

        html = 'aboutme/editprofile.html'
        return render(request, html, response)


def edit_profile(request):
    if 'user_login' in request.session:
        username = request.session.get('user_login')
        edited_user = User.objects.get(username=username)
        if (request.method == 'POST'):
            edited_user.name = request.POST['name']
            edited_user.email = request.POST['email']
            edited_user.linkedin_profile = request.POST['linkedin_profile']
            return HttpResponseRedirect('/aboutme/edit')


def addExpertise(request, expertise, level):
    if 'user_login' in request.session:
        username = request.session.get('user_login')
        user = User.objects.get(username=username)
        expertise = Expertise.objects.filter(expertise=expertise, level=level)

        if expertise == 0:
            e = Expertise.objects.create(expertise=expertise, level=level)
            e.save()
            user.expertise.add(e)
        else:
            user.expertise.add(expertise.first())
        return HttpResponseRedirect('/aboutme/edit')


def showGrades(request):
    if 'user_login' in request.session:
        username = request.session.get('user_login')
        user = User.objects.get(username=username)
        user.flag_nilai = True
        return HttpResponseRedirect('/aboutme/edit')

aboutme/templates/aboutme/aboutme.html
{% extends 'main/layout/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/editprofile.css' %}">
    <link href=' http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <h1 style="text-align:left;">Selamat Datang, {{ username }}</h1>
    <table cellpadding="10">
        <tr>
            <td rowspan="2"><img src="http://www.contribcity.com/images/dummy-profile-pic.png" style="width: 200px">
            </td>
            <td align="right"><input type="button" value="Lihat Forum"></td>
        </tr>
        <tr>
            <td><input type="button" id="buttonedit" value="Edit Profile"
                       onclick="location.href='{% url 'aboutme:edit' %}'">
            </td>
        </tr>
    </table>
    <p></p>
    <p></p>

    <table cellpadding="5" cellspacing="5">
        <tr>
            <td align="left"><h4>Nama</h4></td>
            <td align="left"><h4>{{ name }}</h4></td>
        </tr>
        <tr>
            <td align="left"><h4>NPM</h4></td>
            <td align="left"><h4>{{ npm }}</h4></td>
        </tr>
        <tr>
            <td align="left"><h4>Keahlian</h4></td>
            {% if expertise %}
                {% for object in expertise %}
                    <td align="left"><h4>{{ expertise }}</h4></td>
                {% endfor %}
            {% else %}
                <td align="left"><h4>Kosong</h4></td>
            {% endif %}
        </tr>
        <tr>
            <td align="left"><h4>Email</h4></td>
            <td align="left"><h4>{{ email }}</h4></td>
        </tr>
        <tr>
            <td align="left"><h4>Profil LinkedIn</h4></td>
            <td id="lingin" align="left"><h4>{{ linkedin_profile }}</h4></td>
    </table>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var show_edit = '{{ show_edit }}'
            if (show_edit == 'False') {
                console.log(show_edit)
                $('#buttonedit').hide();
            }
            else {
                $('#buttonedit').show();
            }
        });
    </script>
{% endblock %}

aboutme/templates/aboutme/editprofile.html
{% extends 'main/layout/base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/aboutme.css' %}">
    <link href=' http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>

    <div class="container">
        <center><img id="profilepic" src="{{ profile_pic }}" height="100" width="100" class="img-circle"></center>
        <h4 id="npm" style="text-align: center">NPM</h4>
        <h4 id="npm" style="text-align: center">{{ npm }}</h4>
        <span><button onclick="">SIMPAN</button></span>
        <span><button onclick="">KELUAR</button></span>
        <h2>Data Pribadi</h2>
        <div id="linkedinbutton">
            <p id="baton"></p>
            <div id="profileData" style="display: none;">
                <p id="name"></p>
                <p id="email"></p>
                <p id="linkedInProfile"></p>
            </div>
            <!-- sign in with linkedin button -->
            <script type="in/Login"></script>
        </div>

        <span>
    <p>Tampilkan nilai:</p>
    <input type="radio" id="akses-nilai" value="no"> Tidak
    <input type="radio" id="akses-nilai" value="yes" onclick="location.href='{% url 'aboutme:show-grades' %}'"> Ya
  </span>

        <div id="user-bio"></div>
        <h2>Keahlian</h2>
        <div id="user-skill"></div>
    </div>
    <script src="{% static 'js/aboutme.js' %}"></script>
{% endblock %}