kenalin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import status.urls as status
import aboutme.urls as aboutme

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^aboutme/', include(aboutme, namespace='aboutme')),
    url(r'^academic/', include('academic.urls', namespace='academic')),
    url(r'^auth/', include('main.urls', namespace='main')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^$', RedirectView.as_view(url='auth/', permanent='True')),
]

main/urls.py
from django.conf.urls import url
from .custom_auth import auth_login, auth_logout
from .views import index, login_page
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^sso/$', login_page, name='sso'),
    url(r'^login/$', auth_login, name='login'),
    url(r'^logout/$', auth_logout, name='logout'),
]

main/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


class User(models.Model):
    username = models.CharField(max_length=20, unique=True, primary_key=True)
    npm = models.CharField(max_length=20, unique=True)
    profile_pic = models.URLField(
        default="https://www.lausanne.org/wp-content/uploads/2017/04/anonymous-icon-150x150.jpg")
    flag_nilai = models.BooleanField(default=False)
    name = models.CharField(max_length=27, default="Kosong")
    expertise = models.ManyToManyField('Expertise', default="Kosong")
    email = models.EmailField(default="Kosong")
    linkedin_profile = models.URLField(default="Kosong")


LEVEL_CHOICES = (
    ('1', 'Beginner'),
    ('2', 'Intermediate'),
    ('3', 'Advanced'),
    ('4', 'Expert')
)

class Expertise(models.Model):
    expertise = models.CharField(max_length=20)
    level = models.CharField(max_length=20, choices=LEVEL_CHOICES, default='1')

    def __str__(self):
        return str(self.expertise)

main/views.py
from django.shortcuts import render

res = {}
# Create your views here.
def index(request):
	html = 'main/landing_page.html'
	return render(request, html, res)

def login_page(request):
	html = 'main/login.html'
	return render(request, html, res)

main/templates/main/landing_page.html
{% extends "main/layout/base.html" %}
{% block content %}
<section class="wrap">
	<h1 style="color: #fff; font-size: 70px; background-color: lightblue"><b>kenal.</b><span style="color: black"><b>in</b></span></h1>
	<div class="template">
		<table>
			<tr>
				<td>
					<form action="{% url 'main:sso' %}" method="get">
				    	<button class="btn btn-warning">Login with SSO</button>
					</form>
				</td>
				<td>
					<button class="btn btn-primary">Login with LinkedIn</button>
				</td>
			</tr>
		</table>
	</div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
		$('#header').hide();
    });
</script>
{% endblock %}

main/templates/main/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="gr__sso_ui_ac_id">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sso.css' %}">
    <link rel="icon" href="https://sso.ui.ac.id/cas/themes/ui/logo2_0.gif" type="image/x-icon">
    <title>SSO UI</title>
</head>
<body data-gr-c-s-loaded="true">
        <div class="container">
                <div class="main">



<div class="bg"></div>
<div class="login-box">
        <form id="fm1" class="login" action="{% url 'main:login' %}" method="post">
                {% csrf_token %}
                <div class="top">
                        <div class="pull-right"><img src="https://image.ibb.co/nMCOaG/logo.png"></div>
                        <h1>SSO</h1>
                        <div class="sub">Single Sign On</div>
                </div>


                <div class="middle">
                        <p>Masukkan username dan password UI Anda/<br><em>Enter your username and password</em>:</p>

                                <div class="form-group">



                                    <input id="username" name="username" class="form-control" placeholder="Username" type="text" value="" autocomplete="false">



                                </div>


                                <div class="form-group">
                                        <input id="password" name="password" class="form-control" placeholder="Password" type="password" value="" autocomplete="off">

                                </div>

                </div>
                <div class="bottom clearfix">
                        <div class="pull-right" style="margin-top:12px">
                                <button type="submit" class="btn btn-lg btn-primary">Login</button>
                        </div>
            <table>
              <tbody><tr>
<!--
                <td style="padding: 10px 10px 10px 10px;">
                        <div class="help"><a href="#">Lupa password<br /><em>Forget password</em></a></div>
                </td>
-->
                <td style="padding: 0px 10px 10px 10px;">
                        <div class="help"><a href="https://sso.ui.ac.id/account/user/register">Daftar Akun<br><em>Guest Account</em></a></div>
                </td>
                <td style="border-left: solid #D5D5D5; ">
                </td>
                <td style="padding: 0px 0px 10px 10px;">
                        <div class="help"><a href="https://sso.ui.ac.id/account/static/frequently-asked-question-faq">Butuh Bantuan ?<br><em>Need Help ?</em></a></div>
                </td>
              </tr>
            </tbody></table>
                </div>
        </form>
</div>

<script type="text/javascript">
function hasError(input) {
        if (input && /has-error/.test(input.parentElement.className)) return input;
}
function isEmpty(input) {
        if (input && input.value == "") return input;
}
var u = document.getElementById("username");
var p = document.getElementById("password");
var candidates = [hasError(u), hasError(p), isEmpty(u), isEmpty(p), u];
for (var i = 0; i < candidates.length; ++i) {
        if (candidates[i]) {
                candidates[i].focus();
                break;
        }
}
</script>





</div></div></body></html>